test_that("a sampler written from the blocks reproduces gibbs() step by step", {
  src <- readLines(system.file("examples", "ex07_blocks.R", package = "birtRcpp"))
  eval(parse(text = src[1:(grep("^set.seed[(]7[)]", src) - 1)]))
  set.seed(8)
  cond <- set_cond(n_subj = 150, n_item = 5)
  m <- rtirt_cross(sim_data(cond, sim_para(cond, "cross"), "cross"))
  r <- cross_sampler(m, n_iter = 300, seed = 2)
  cpp <- as.matrix(gibbs(m, n_iter = 300, n_chain = 1, seed = 2, verbose = FALSE, fit_indices = FALSE)$post$draws)
  expect_lt(max(abs(r - cpp)), 1e-10)
})

test_that("the blocks return draws of the right shape", {
  set.seed(9)
  expect_length(draw_gauss(c(1, 2, 3), c(0, 0, 0)), 3)
  expect_true(all(draw_invgamma(2, c(1, 2)) > 0))
  x <- draw_tnorm(rep(0, 50), 1, 0, 1); expect_true(all(x >= 0 & x <= 1))
  th <- rnorm(40); Y <- matrix(rbinom(120, 1, 0.5), 40)
  om <- draw_omega(rep(1, 3), rep(0, 3), th); expect_equal(dim(om), c(40, 3)); expect_true(all(om > 0))
  ip <- irt_part(Y, om, rep(1, 3), rep(0, 3)); expect_named(ip, c("prec", "num")); expect_length(ip$prec, 40)
  ab <- draw_items_joint(Y, th, rep(1, 3), rep(0, 3)); expect_named(ab, c("a", "b")); expect_length(attr(ab, "accepted"), 3)
  expect_true(all(draw_items_pg(Y, om, th, rep(1, 3), one_pl = TRUE)$a == 1))
  nu <- draw_nu(matrix(rnorm(120), 40), matrix(0.5, 40, 3), 0.25); expect_true(all(nu > 0))
  expect_error(draw_sigma2(matrix(1, 2, 2), matrix(0, 2, 2), c(1, 1), nu = matrix(1, 2, 2)), "needs q")
  expect_error(draw_sigma2(matrix(c(1, NA, 1, 1), 2), matrix(0, 2, 2), c(1, 1), c(1, 1)), "contain NA")
  expect_error(draw_lambda(matrix(c(1, NA, 1, 1), 2), matrix(0, 2, 2), matrix(0, 2, 2), matrix(1, 2, 2), 0, 10), "contain NA")
  expect_error(draw_items_pg(Y, om, th, rep(1, 3), priors = list()), "rtirt_priors")
})

test_that("draw_pg() draws PG(1, eta) and equals draw_omega() for eta = a (theta - b)", {
  theta <- c(-1, 0, 2); a <- c(0.5, 1.5); b <- c(0, 1)
  set.seed(9); w1 <- draw_omega(a, b, theta)
  set.seed(9); w2 <- draw_pg(sweep(outer(theta, a), 2, a * b))
  expect_identical(w1, w2)
  set.seed(10); z <- c(0, 1, 4)
  w <- draw_pg(matrix(z, 20000, 3, byrow = TRUE))
  expect_equal(colMeans(w), c(0.25, tanh(0.5) / 2, tanh(2) / 8), tolerance = 0.02)
})

test_that("draw_probit_z() draws the truncated latent responses of Albert & Chib (1993)", {
  set.seed(11); eta <- matrix(c(-1, 0.5, 2), 30000, 3, byrow = TRUE)
  Y <- matrix(rep(c(1, 0, NA), each = 30000), 30000)
  z <- draw_probit_z(Y, eta)
  expect_true(all(z[, 1] > 0)); expect_true(all(z[, 2] < 0))
  expect_equal(mean(z[, 1]), -1 + dnorm(-1) / pnorm(-1) * 0 + dnorm(1) / pnorm(-1), tolerance = 0.01)   # E[z | z > 0], z ~ N(-1, 1)
  expect_equal(c(mean(z[, 3]), sd(z[, 3])), c(2, 1), tolerance = 0.02)
})
