// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// item_chain
arma::mat item_chain(const arma::vec& y, const arma::vec& theta, int n_iter, bool joint);
RcppExport SEXP _birtRcpp_item_chain(SEXP ySEXP, SEXP thetaSEXP, SEXP n_iterSEXP, SEXP jointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type joint(jointSEXP);
    rcpp_result_gen = Rcpp::wrap(item_chain(y, theta, n_iter, joint));
    return rcpp_result_gen;
END_RCPP
}
// blk_gauss
arma::vec blk_gauss(const arma::vec& prec, const arma::vec& num);
RcppExport SEXP _birtRcpp_blk_gauss(SEXP precSEXP, SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type prec(precSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type num(numSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_gauss(prec, num));
    return rcpp_result_gen;
END_RCPP
}
// blk_invgamma
arma::vec blk_invgamma(const arma::vec& shape, const arma::vec& scale);
RcppExport SEXP _birtRcpp_blk_invgamma(SEXP shapeSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_invgamma(shape, scale));
    return rcpp_result_gen;
END_RCPP
}
// blk_tnorm
arma::vec blk_tnorm(const arma::vec& mean, const arma::vec& sd, double lo, double hi);
RcppExport SEXP _birtRcpp_blk_tnorm(SEXP meanSEXP, SEXP sdSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_tnorm(mean, sd, lo, hi));
    return rcpp_result_gen;
END_RCPP
}
// blk_omega
arma::mat blk_omega(const arma::vec& a, const arma::vec& b, const arma::vec& theta);
RcppExport SEXP _birtRcpp_blk_omega(SEXP aSEXP, SEXP bSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_omega(a, b, theta));
    return rcpp_result_gen;
END_RCPP
}
// blk_pg
arma::mat blk_pg(const arma::mat& eta);
RcppExport SEXP _birtRcpp_blk_pg(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_pg(eta));
    return rcpp_result_gen;
END_RCPP
}
// blk_probit_z
arma::mat blk_probit_z(const arma::mat& Y, const arma::mat& eta);
RcppExport SEXP _birtRcpp_blk_probit_z(SEXP YSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_probit_z(Y, eta));
    return rcpp_result_gen;
END_RCPP
}
// blk_irt_part
Rcpp::List blk_irt_part(const arma::mat& Y, const arma::mat& omega, const arma::vec& a, const arma::vec& b);
RcppExport SEXP _birtRcpp_blk_irt_part(SEXP YSEXP, SEXP omegaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_irt_part(Y, omega, a, b));
    return rcpp_result_gen;
END_RCPP
}
// blk_items_pg
Rcpp::List blk_items_pg(const arma::mat& Y, const arma::mat& omega, const arma::vec& theta, arma::vec a, const Rcpp::NumericVector& prior, bool one_pl, const arma::vec& b_mu);
RcppExport SEXP _birtRcpp_blk_items_pg(SEXP YSEXP, SEXP omegaSEXP, SEXP thetaSEXP, SEXP aSEXP, SEXP priorSEXP, SEXP one_plSEXP, SEXP b_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< bool >::type one_pl(one_plSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b_mu(b_muSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_items_pg(Y, omega, theta, a, prior, one_pl, b_mu));
    return rcpp_result_gen;
END_RCPP
}
// blk_items_joint
Rcpp::List blk_items_joint(const arma::mat& Y, const arma::vec& theta, arma::vec a, arma::vec b, const Rcpp::NumericVector& prior, const arma::vec& b_mu);
RcppExport SEXP _birtRcpp_blk_items_joint(SEXP YSEXP, SEXP thetaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP priorSEXP, SEXP b_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b_mu(b_muSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_items_joint(Y, theta, a, b, prior, b_mu));
    return rcpp_result_gen;
END_RCPP
}
// blk_lambda
arma::vec blk_lambda(const arma::mat& L, const arma::mat& m, const arma::mat& k1nu, const arma::mat& W, double mu_l, double sd_l, double lo_l);
RcppExport SEXP _birtRcpp_blk_lambda(SEXP LSEXP, SEXP mSEXP, SEXP k1nuSEXP, SEXP WSEXP, SEXP mu_lSEXP, SEXP sd_lSEXP, SEXP lo_lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type k1nu(k1nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type mu_l(mu_lSEXP);
    Rcpp::traits::input_parameter< double >::type sd_l(sd_lSEXP);
    Rcpp::traits::input_parameter< double >::type lo_l(lo_lSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_lambda(L, m, k1nu, W, mu_l, sd_l, lo_l));
    return rcpp_result_gen;
END_RCPP
}
// blk_sigma2
arma::vec blk_sigma2(const arma::mat& L, const arma::mat& m, const arma::vec& lambda, const Rcpp::NumericVector& prior, Rcpp::Nullable<Rcpp::NumericMatrix> nu, double q, const arma::vec& current);
RcppExport SEXP _birtRcpp_blk_sigma2(SEXP LSEXP, SEXP mSEXP, SEXP lambdaSEXP, SEXP priorSEXP, SEXP nuSEXP, SEXP qSEXP, SEXP currentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type current(currentSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_sigma2(L, m, lambda, prior, nu, q, current));
    return rcpp_result_gen;
END_RCPP
}
// blk_nu
arma::mat blk_nu(const arma::mat& r, const arma::mat& s, double q);
RcppExport SEXP _birtRcpp_blk_nu(SEXP rSEXP, SEXP sSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_nu(r, s, q));
    return rcpp_result_gen;
END_RCPP
}
// blk_theta_collapsed
arma::vec blk_theta_collapsed(const arma::vec& prec, const arma::vec& num, const arma::mat& W, const arma::mat& y, const arma::vec& rho, const arma::vec& m0, const arma::vec& g, const arma::vec& tau);
RcppExport SEXP _birtRcpp_blk_theta_collapsed(SEXP precSEXP, SEXP numSEXP, SEXP WSEXP, SEXP ySEXP, SEXP rhoSEXP, SEXP m0SEXP, SEXP gSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type prec(precSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type num(numSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_theta_collapsed(prec, num, W, y, rho, m0, g, tau));
    return rcpp_result_gen;
END_RCPP
}
// blk_rt_items_collapsed
Rcpp::List blk_rt_items_collapsed(const arma::mat& L, const arma::mat& k1nu, const arma::mat& W, const arma::vec& theta, const arma::vec& mz, const arma::vec& tau, bool with_rho, double mu_l, double sd_l, double rho_sd, arma::vec lambda, arma::vec rho, double lo_l);
RcppExport SEXP _birtRcpp_blk_rt_items_collapsed(SEXP LSEXP, SEXP k1nuSEXP, SEXP WSEXP, SEXP thetaSEXP, SEXP mzSEXP, SEXP tauSEXP, SEXP with_rhoSEXP, SEXP mu_lSEXP, SEXP sd_lSEXP, SEXP rho_sdSEXP, SEXP lambdaSEXP, SEXP rhoSEXP, SEXP lo_lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type k1nu(k1nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type with_rho(with_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu_l(mu_lSEXP);
    Rcpp::traits::input_parameter< double >::type sd_l(sd_lSEXP);
    Rcpp::traits::input_parameter< double >::type rho_sd(rho_sdSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type lo_l(lo_lSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_rt_items_collapsed(L, k1nu, W, theta, mz, tau, with_rho, mu_l, sd_l, rho_sd, lambda, rho, lo_l));
    return rcpp_result_gen;
END_RCPP
}
// blk_var
double blk_var(double alpha, double beta, double fam, double p1, double p2, double current);
RcppExport SEXP _birtRcpp_blk_var(SEXP alphaSEXP, SEXP betaSEXP, SEXP famSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP currentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type fam(famSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type current(currentSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_var(alpha, beta, fam, p1, p2, current));
    return rcpp_result_gen;
END_RCPP
}
// blk_mvn
arma::mat blk_mvn(const arma::cube& Q, const arma::mat& h, const arma::vec& lower, const arma::vec& upper, int max_tries);
RcppExport SEXP _birtRcpp_blk_mvn(SEXP QSEXP, SEXP hSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP max_triesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type max_tries(max_triesSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_mvn(Q, h, lower, upper, max_tries));
    return rcpp_result_gen;
END_RCPP
}
// blk_items_mh
Rcpp::List blk_items_mh(const arma::mat& Y, const arma::vec& theta, arma::vec a, arma::vec b, const arma::mat& mean, const arma::mat& P, int link, int form);
RcppExport SEXP _birtRcpp_blk_items_mh(SEXP YSEXP, SEXP thetaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP meanSEXP, SEXP PSEXP, SEXP linkSEXP, SEXP formSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type form(formSEXP);
    rcpp_result_gen = Rcpp::wrap(blk_items_mh(Y, theta, a, b, mean, P, link, form));
    return rcpp_result_gen;
END_RCPP
}
// em_loglik_nodes
arma::mat em_loglik_nodes(const arma::mat& Y, const arma::vec& a, const arma::vec& b, const arma::mat& TH);
RcppExport SEXP _birtRcpp_em_loglik_nodes(SEXP YSEXP, SEXP aSEXP, SEXP bSEXP, SEXP THSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TH(THSEXP);
    rcpp_result_gen = Rcpp::wrap(em_loglik_nodes(Y, a, b, TH));
    return rcpp_result_gen;
END_RCPP
}
// em_item_sums
Rcpp::List em_item_sums(const arma::mat& Y, const arma::vec& a, const arma::vec& b, const arma::mat& TH, const arma::mat& W, bool score);
RcppExport SEXP _birtRcpp_em_item_sums(SEXP YSEXP, SEXP aSEXP, SEXP bSEXP, SEXP THSEXP, SEXP WSEXP, SEXP scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type TH(THSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type score(scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(em_item_sums(Y, a, b, TH, W, score));
    return rcpp_result_gen;
END_RCPP
}
// pg_mean_vec
Rcpp::NumericVector pg_mean_vec(const Rcpp::NumericVector& eta);
RcppExport SEXP _birtRcpp_pg_mean_vec(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(pg_mean_vec(eta));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_cross
Rcpp::List gibbs_cross(const arma::mat& Y, const arma::mat& L, bool ald, double q, bool cov2one, bool one_pl, bool collapse, bool ab_joint, int n_iter, int n_burn, Rcpp::List init, Rcpp::NumericVector prior);
RcppExport SEXP _birtRcpp_gibbs_cross(SEXP YSEXP, SEXP LSEXP, SEXP aldSEXP, SEXP qSEXP, SEXP cov2oneSEXP, SEXP one_plSEXP, SEXP collapseSEXP, SEXP ab_jointSEXP, SEXP n_iterSEXP, SEXP n_burnSEXP, SEXP initSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< bool >::type ald(aldSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type cov2one(cov2oneSEXP);
    Rcpp::traits::input_parameter< bool >::type one_pl(one_plSEXP);
    Rcpp::traits::input_parameter< bool >::type collapse(collapseSEXP);
    Rcpp::traits::input_parameter< bool >::type ab_joint(ab_jointSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_cross(Y, L, ald, q, cov2one, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_latent
Rcpp::List gibbs_latent(const arma::mat& Y, const arma::mat& L, const arma::mat& X, bool ald, double q, bool one_pl, bool collapse, bool ab_joint, int n_iter, int n_burn, Rcpp::List init, Rcpp::NumericVector prior);
RcppExport SEXP _birtRcpp_gibbs_latent(SEXP YSEXP, SEXP LSEXP, SEXP XSEXP, SEXP aldSEXP, SEXP qSEXP, SEXP one_plSEXP, SEXP collapseSEXP, SEXP ab_jointSEXP, SEXP n_iterSEXP, SEXP n_burnSEXP, SEXP initSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type ald(aldSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type one_pl(one_plSEXP);
    Rcpp::traits::input_parameter< bool >::type collapse(collapseSEXP);
    Rcpp::traits::input_parameter< bool >::type ab_joint(ab_jointSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_latent(Y, L, X, ald, q, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_mlirt
Rcpp::List gibbs_mlirt(const arma::mat& Y, const arma::mat& X, bool one_pl, bool collapse, bool ab_joint, int n_iter, int n_burn, Rcpp::List init, Rcpp::NumericVector prior);
RcppExport SEXP _birtRcpp_gibbs_mlirt(SEXP YSEXP, SEXP XSEXP, SEXP one_plSEXP, SEXP collapseSEXP, SEXP ab_jointSEXP, SEXP n_iterSEXP, SEXP n_burnSEXP, SEXP initSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type one_pl(one_plSEXP);
    Rcpp::traits::input_parameter< bool >::type collapse(collapseSEXP);
    Rcpp::traits::input_parameter< bool >::type ab_joint(ab_jointSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_mlirt(Y, X, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_rtirt
Rcpp::List gibbs_rtirt(const arma::mat& Y, const arma::mat& L, const arma::mat& X, bool cov2one, bool one_pl, bool collapse, bool ab_joint, int n_iter, int n_burn, Rcpp::List init, Rcpp::NumericVector prior);
RcppExport SEXP _birtRcpp_gibbs_rtirt(SEXP YSEXP, SEXP LSEXP, SEXP XSEXP, SEXP cov2oneSEXP, SEXP one_plSEXP, SEXP collapseSEXP, SEXP ab_jointSEXP, SEXP n_iterSEXP, SEXP n_burnSEXP, SEXP initSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type cov2one(cov2oneSEXP);
    Rcpp::traits::input_parameter< bool >::type one_pl(one_plSEXP);
    Rcpp::traits::input_parameter< bool >::type collapse(collapseSEXP);
    Rcpp::traits::input_parameter< bool >::type ab_joint(ab_jointSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_rtirt(Y, L, X, cov2one, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior));
    return rcpp_result_gen;
END_RCPP
}
// log_ald_rt_cpp
Rcpp::NumericVector log_ald_rt_cpp(const arma::mat& B, const arma::vec& s, double v, double q);
RcppExport SEXP _birtRcpp_log_ald_rt_cpp(SEXP BSEXP, SEXP sSEXP, SEXP vSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(log_ald_rt_cpp(B, s, v, q));
    return rcpp_result_gen;
END_RCPP
}
// ml_eval
Rcpp::NumericMatrix ml_eval(const Rcpp::NumericVector& coef, const Rcpp::List& ids, const Rcpp::List& vals, const Rcpp::IntegerVector& dims, int nr, int nc);
RcppExport SEXP _birtRcpp_ml_eval(SEXP coefSEXP, SEXP idsSEXP, SEXP valsSEXP, SEXP dimsSEXP, SEXP nrSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(ml_eval(coef, ids, vals, dims, nr, nc));
    return rcpp_result_gen;
END_RCPP
}
// ml_part
Rcpp::List ml_part(const Rcpp::List& c1, const Rcpp::List& r0, const Rcpp::List& third, SEXP om_, SEXP mask_, SEXP kappa_, SEXP roww_, int mode, int red, int nr, int nc, bool keep_om);
RcppExport SEXP _birtRcpp_ml_part(SEXP c1SEXP, SEXP r0SEXP, SEXP thirdSEXP, SEXP om_SEXP, SEXP mask_SEXP, SEXP kappa_SEXP, SEXP roww_SEXP, SEXP modeSEXP, SEXP redSEXP, SEXP nrSEXP, SEXP ncSEXP, SEXP keep_omSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type third(thirdSEXP);
    Rcpp::traits::input_parameter< SEXP >::type om_(om_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type mask_(mask_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type kappa_(kappa_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type roww_(roww_SEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< int >::type red(redSEXP);
    Rcpp::traits::input_parameter< int >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_om(keep_omSEXP);
    rcpp_result_gen = Rcpp::wrap(ml_part(c1, r0, third, om_, mask_, kappa_, roww_, mode, red, nr, nc, keep_om));
    return rcpp_result_gen;
END_RCPP
}
// rpg1_r
Rcpp::NumericVector rpg1_r(Rcpp::NumericVector z);
RcppExport SEXP _birtRcpp_rpg1_r(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rpg1_r(z));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm_r
Rcpp::NumericVector rtnorm_r(int n, double mu, double sd, double lo, double hi);
RcppExport SEXP _birtRcpp_rtnorm_r(SEXP nSEXP, SEXP muSEXP, SEXP sdSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm_r(n, mu, sd, lo, hi));
    return rcpp_result_gen;
END_RCPP
}
// rinvgauss_r
Rcpp::NumericVector rinvgauss_r(int n, double mu, double lambda);
RcppExport SEXP _birtRcpp_rinvgauss_r(SEXP nSEXP, SEXP muSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(rinvgauss_r(n, mu, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_birtRcpp_item_chain", (DL_FUNC) &_birtRcpp_item_chain, 4},
    {"_birtRcpp_blk_gauss", (DL_FUNC) &_birtRcpp_blk_gauss, 2},
    {"_birtRcpp_blk_invgamma", (DL_FUNC) &_birtRcpp_blk_invgamma, 2},
    {"_birtRcpp_blk_tnorm", (DL_FUNC) &_birtRcpp_blk_tnorm, 4},
    {"_birtRcpp_blk_omega", (DL_FUNC) &_birtRcpp_blk_omega, 3},
    {"_birtRcpp_blk_pg", (DL_FUNC) &_birtRcpp_blk_pg, 1},
    {"_birtRcpp_blk_probit_z", (DL_FUNC) &_birtRcpp_blk_probit_z, 2},
    {"_birtRcpp_blk_irt_part", (DL_FUNC) &_birtRcpp_blk_irt_part, 4},
    {"_birtRcpp_blk_items_pg", (DL_FUNC) &_birtRcpp_blk_items_pg, 7},
    {"_birtRcpp_blk_items_joint", (DL_FUNC) &_birtRcpp_blk_items_joint, 6},
    {"_birtRcpp_blk_lambda", (DL_FUNC) &_birtRcpp_blk_lambda, 7},
    {"_birtRcpp_blk_sigma2", (DL_FUNC) &_birtRcpp_blk_sigma2, 7},
    {"_birtRcpp_blk_nu", (DL_FUNC) &_birtRcpp_blk_nu, 3},
    {"_birtRcpp_blk_theta_collapsed", (DL_FUNC) &_birtRcpp_blk_theta_collapsed, 8},
    {"_birtRcpp_blk_rt_items_collapsed", (DL_FUNC) &_birtRcpp_blk_rt_items_collapsed, 13},
    {"_birtRcpp_blk_var", (DL_FUNC) &_birtRcpp_blk_var, 6},
    {"_birtRcpp_blk_mvn", (DL_FUNC) &_birtRcpp_blk_mvn, 5},
    {"_birtRcpp_blk_items_mh", (DL_FUNC) &_birtRcpp_blk_items_mh, 8},
    {"_birtRcpp_em_loglik_nodes", (DL_FUNC) &_birtRcpp_em_loglik_nodes, 4},
    {"_birtRcpp_em_item_sums", (DL_FUNC) &_birtRcpp_em_item_sums, 6},
    {"_birtRcpp_pg_mean_vec", (DL_FUNC) &_birtRcpp_pg_mean_vec, 1},
    {"_birtRcpp_gibbs_cross", (DL_FUNC) &_birtRcpp_gibbs_cross, 12},
    {"_birtRcpp_gibbs_latent", (DL_FUNC) &_birtRcpp_gibbs_latent, 12},
    {"_birtRcpp_gibbs_mlirt", (DL_FUNC) &_birtRcpp_gibbs_mlirt, 9},
    {"_birtRcpp_gibbs_rtirt", (DL_FUNC) &_birtRcpp_gibbs_rtirt, 11},
    {"_birtRcpp_log_ald_rt_cpp", (DL_FUNC) &_birtRcpp_log_ald_rt_cpp, 4},
    {"_birtRcpp_ml_eval", (DL_FUNC) &_birtRcpp_ml_eval, 6},
    {"_birtRcpp_ml_part", (DL_FUNC) &_birtRcpp_ml_part, 12},
    {"_birtRcpp_rpg1_r", (DL_FUNC) &_birtRcpp_rpg1_r, 1},
    {"_birtRcpp_rtnorm_r", (DL_FUNC) &_birtRcpp_rtnorm_r, 5},
    {"_birtRcpp_rinvgauss_r", (DL_FUNC) &_birtRcpp_rinvgauss_r, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_birtRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
