# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.item_chain <- function(y, theta, n_iter, joint) {
    .Call(`_birtRcpp_item_chain`, y, theta, n_iter, joint)
}

.blk_gauss <- function(prec, num) {
    .Call(`_birtRcpp_blk_gauss`, prec, num)
}

.blk_invgamma <- function(shape, scale) {
    .Call(`_birtRcpp_blk_invgamma`, shape, scale)
}

.blk_tnorm <- function(mean, sd, lo, hi) {
    .Call(`_birtRcpp_blk_tnorm`, mean, sd, lo, hi)
}

.blk_omega <- function(a, b, theta) {
    .Call(`_birtRcpp_blk_omega`, a, b, theta)
}

.blk_pg <- function(eta) {
    .Call(`_birtRcpp_blk_pg`, eta)
}

.blk_probit_z <- function(Y, eta) {
    .Call(`_birtRcpp_blk_probit_z`, Y, eta)
}

.blk_irt_part <- function(Y, omega, a, b) {
    .Call(`_birtRcpp_blk_irt_part`, Y, omega, a, b)
}

.blk_items_pg <- function(Y, omega, theta, a, prior, one_pl, b_mu) {
    .Call(`_birtRcpp_blk_items_pg`, Y, omega, theta, a, prior, one_pl, b_mu)
}

.blk_items_joint <- function(Y, theta, a, b, prior, b_mu) {
    .Call(`_birtRcpp_blk_items_joint`, Y, theta, a, b, prior, b_mu)
}

.blk_lambda <- function(L, m, k1nu, W, mu_l, sd_l, lo_l) {
    .Call(`_birtRcpp_blk_lambda`, L, m, k1nu, W, mu_l, sd_l, lo_l)
}

.blk_sigma2 <- function(L, m, lambda, prior, nu, q, current) {
    .Call(`_birtRcpp_blk_sigma2`, L, m, lambda, prior, nu, q, current)
}

.blk_nu <- function(r, s, q) {
    .Call(`_birtRcpp_blk_nu`, r, s, q)
}

.blk_theta_collapsed <- function(prec, num, W, y, rho, m0, g, tau) {
    .Call(`_birtRcpp_blk_theta_collapsed`, prec, num, W, y, rho, m0, g, tau)
}

.blk_rt_items_collapsed <- function(L, k1nu, W, theta, mz, tau, with_rho, mu_l, sd_l, rho_sd, lambda, rho, lo_l) {
    .Call(`_birtRcpp_blk_rt_items_collapsed`, L, k1nu, W, theta, mz, tau, with_rho, mu_l, sd_l, rho_sd, lambda, rho, lo_l)
}

.blk_var <- function(alpha, beta, fam, p1, p2, current) {
    .Call(`_birtRcpp_blk_var`, alpha, beta, fam, p1, p2, current)
}

.blk_mvn <- function(Q, h, lower, upper, max_tries) {
    .Call(`_birtRcpp_blk_mvn`, Q, h, lower, upper, max_tries)
}

.blk_items_mh <- function(Y, theta, a, b, mean, P, link, form) {
    .Call(`_birtRcpp_blk_items_mh`, Y, theta, a, b, mean, P, link, form)
}

.em_loglik_nodes <- function(Y, a, b, TH) {
    .Call(`_birtRcpp_em_loglik_nodes`, Y, a, b, TH)
}

.em_item_sums <- function(Y, a, b, TH, W, score) {
    .Call(`_birtRcpp_em_item_sums`, Y, a, b, TH, W, score)
}

pg_mean <- function(eta) {
    .Call(`_birtRcpp_pg_mean_vec`, eta)
}

.gibbs_cross <- function(Y, L, ald, q, cov2one, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior) {
    .Call(`_birtRcpp_gibbs_cross`, Y, L, ald, q, cov2one, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior)
}

.gibbs_latent <- function(Y, L, X, ald, q, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior) {
    .Call(`_birtRcpp_gibbs_latent`, Y, L, X, ald, q, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior)
}

.gibbs_mlirt <- function(Y, X, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior) {
    .Call(`_birtRcpp_gibbs_mlirt`, Y, X, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior)
}

.gibbs_rtirt <- function(Y, L, X, cov2one, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior) {
    .Call(`_birtRcpp_gibbs_rtirt`, Y, L, X, cov2one, one_pl, collapse, ab_joint, n_iter, n_burn, init, prior)
}

.log_ald_rt <- function(B, s, v, q) {
    .Call(`_birtRcpp_log_ald_rt_cpp`, B, s, v, q)
}

.ml_eval <- function(coef, ids, vals, dims, nr, nc) {
    .Call(`_birtRcpp_ml_eval`, coef, ids, vals, dims, nr, nc)
}

.ml_part <- function(c1, r0, third, om_, mask_, kappa_, roww_, mode, red, nr, nc, keep_om = FALSE) {
    .Call(`_birtRcpp_ml_part`, c1, r0, third, om_, mask_, kappa_, roww_, mode, red, nr, nc, keep_om)
}

.rpg1 <- function(z) {
    .Call(`_birtRcpp_rpg1_r`, z)
}

.rtnorm <- function(n, mu, sd, lo, hi) {
    .Call(`_birtRcpp_rtnorm_r`, n, mu, sd, lo, hi)
}

.rinvgauss <- function(n, mu, lambda) {
    .Call(`_birtRcpp_rinvgauss_r`, n, mu, lambda)
}

